amcl:
  ros__parameters:
    use_sim_time: false
    base_frame_id: "base_footprint"
    odom_frame_id: "odom"
    scan_topic: "scan"
    min_particles: 500
    max_particles: 2000
    laser_min_range: 0.02  # For Okdo LD06 Lidar.
    laser_max_range: 12.0  # For Okdo LD06 Lidar.
    set_initial_pose: true
    update_min_d: 0.1
    update_min_a: 0.2
    resample_interval: 1
    transform_tolerance: 1.0
    #transform_tolerance: 0.3

map_server:
  ros__parameters:
    use_sim_time: false
    #yaml_filename: "/home/fk/ros2_wheelrobot_ws/src/robot_nav2_bringup/map/my_map.yaml"
    yaml_filename: "~/ros2_wheelrobot_ws/src/robot_nav2_bringup/map/my_map.yaml"


map_saver:
  ros__parameters:
    use_sim_time: false
    save_map_timeout: 5.0
    free_thresh_default: 0.25
    occupied_thresh_default: 0.65

planner_server:
  ros__parameters:
    use_sim_time: false
    #expected_planner_frequency: 10.0  # Try to match this to the /scan frequency.
    planner_plugins: ["GridBased"]
    GridBased:
      plugin: "nav2_navfn_planner::NavfnPlanner"
      tolerance: 0.5
      use_astar: false
      allow_unknown: true

controller_server:
  ros__parameters:
    use_sim_time: false
    controller_frequency: 10.0  # Try to match this to the /scan frequency.
    controller_plugins: ["FollowPath"]
    FollowPath:
      plugin: "nav2_regulated_pure_pursuit_controller::RegulatedPurePursuitController"
      max_linear_velocity: 0.25
      min_linear_velocity: 0.05
      max_angular_velocity: 1.571
      min_lookahead_dist: 0.3
      lookahead_time: 1.5
      rotate_to_heading_angular_vel: 0.5

bt_navigator:
  ros__parameters:
    use_sim_time: false
    global_frame: map
    robot_base_frame: base_footprint
    transform_tolerance: 0.5  
    default_nav_to_poses_bt_xml: "/opt/ros/jazzy/share/nav2_bt_navigator/behavior_trees/navigate_to_poses_w_replanning_and_recovery.xml"
    default_nav_through_poses_bt_xml: "/opt/ros/jazzy/share/nav2_bt_navigator/behavior_trees/navigate_through_poses_w_replanning_and_recovery.xml"
    #default_nav_to_pose_bt_xml: "navigate_to_poses_w_replanning_and_recovery.xml"
    #default_nav_through_poses_bt_xml: "navigate_through_poses_w_replanning_and_recovery.xml"

behavior_server:
  ros__parameters:
    use_sim_time: false
    behavior_plugins: ["spin", "backup", "wait"]
    spin:
      plugin: "nav2_behaviors::Spin" # In Iron and older versions, "/" was used instead of "::"
    backup:
      plugin: "nav2_behaviors::BackUp" # In Iron and older versions, "/" was used instead of "::"
    wait:
      plugin: "nav2_behaviors::Wait" # In Iron and older versions, "/" was used instead of "::"

local_costmap:
  local_costmap:
    ros__parameters:
      update_frequency: 5.0
      publish_frequency: 2.0
      global_frame: "odom"
      robot_base_frame: "base_footprint"
      #transform_tolerance: 1.0 
      transform_tolerance: 0.3
      use_sim_time: false
      rolling_window: true
      width: 3    # 2m x 2m local costmap, for small robot
      height: 3
      resolution: 0.05
      footprint: "[[-0.1, -0.115], [-0.1, 0.115], [0.1, 0.115], [0.1, -0.115]]"
      plugins: ["obstacle_layer", "inflation_layer"]
      obstacle_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"
        observation_sources: scan
        scan:
          topic: "scan"
          max_obstacle_height: 2.0
          clearing: true
          marking: true
          data_type: "LaserScan"
          obstacle_range: 12.0
          raytrace_range: 13.0
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        inflation_radius: 0.2

global_costmap:
  global_costmap:
    ros__parameters:
      update_frequency: 1.0
      publish_frequency: 1.0
      global_frame: "map"
      robot_base_frame: "base_footprint"
      #transform_tolerance: 1.0
      transform_tolerance: 0.3
      use_sim_time: false
      rolling_window: false
      width: 10
      height: 10
      resolution: 0.05
      footprint: "[[-0.1, -0.115], [-0.1, 0.115], [0.1, 0.115], [0.1, -0.115]]"
      plugins: ["static_layer", "obstacle_layer", "inflation_layer"]
      static_layer:
        plugin: "nav2_costmap_2d::StaticLayer"
      obstacle_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"
        observation_sources: scan
        scan:
          topic: "scan"
          max_obstacle_height: 2.0
          clearing: true
          marking: true
          data_type: "LaserScan"
          obstacle_range: 12.0
          raytrace_range: 13.0
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        inflation_radius: 0.3
